version: '3.7'
volumes:
    postgres:
    node_modules:
services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./localSetup/postgres/initial-setup.sql:/docker-entrypoint-initdb.d/init-db.sql
        ports:
            - '5432:5432'

    api:
        command: "/bin/sh -c '/start-scripts/wait-for-multiple.sh postgres:5432; yarn; yarn typeorm migration:run; yarn start:dev'"
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - ./src:/app/src
            - node_modules:/app/node_modules
            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - ./.env.defaults:/app/.env.defaults
            - ./tsconfig.json:/app/tsconfig.json
            - ./tslint.json:/app/tslint.json
            - ./localSetup/helpers/start-scripts:/start-scripts
        ports:
            - '80:80'
